#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     SONAR,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          LEFT,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RIGHT,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int currentPower = 20, thresHold = 13, colorReflectiveValue,currentDistance, error, slewRate = 25;
float k = 5, nTurnRatio = 0,desiredNTurnRatio;


void slewNTurnRatioControl(){

	repeatUntil(nTurnRatio == desiredNTurnRatio){

		error = (float)(colorReflectiveValue - thresHold);

		/*	if(desiredNTurnRatio < 0){
		k = 4;
		desiredNTurnRatio = -(k * error);
		currentPower = 25;
		}
		else{
		k = 2;
		currentPower = 20;
		desiredNTurnRatio = -(k * error);
		}
		*/
		desiredNTurnRatio = -(k * error);
		if(nTurnRatio < desiredNTurnRatio){
			if(nTurnRatio  + slewRate < desiredNTurnRatio)
				nTurnRatio  += slewRate;
			else
				nTurnRatio  = desiredNTurnRatio;
		}
		else if(nTurnRatio > desiredNTurnRatio){
			if(nTurnRatio - slewRate > desiredNTurnRatio)
				nTurnRatio  -= slewRate;
			else
				nTurnRatio = desiredNTurnRatio;
		}
	}// END OF repeatUntil()
}// END OF slewRatecontrol()

// task to read range sensor
task readDistance(){
	while(true){
		currentDistance = getUSDistance(SONAR);
	}
}

task readColorReflective(){
	while(true){
		colorReflectiveValue = getColorReflected(colorSensor);
		displayBigTextLine(5,"CR: %i",colorReflectiveValue);
	}// END OF WHILE LOOP
}// END OF readColorReflective()

task controllerTask(){
	while(true){

		error = (float)(colorReflectiveValue - thresHold);
		if(currentDistance < 9){
			nTurnRatio = 100;
			delay(500);
			nTurnRatio = 0;
			delay(2000);
			nTurnRatio = -100;
			delay(800);
			nTurnRatio = 0;
			delay(2800);
			nTurnRatio = -100;
			delay(900);
			nTurnRatio = 0;
			delay(2000);
		}
		if(colorReflectiveValue < thresHold || colorReflectiveValue > thresHold ){
			desiredNTurnRatio = -(k * error);
			slewNTurnRatioControl();
		}
	}// END OF WHILE LOOP
}// END OF readColorReflective()



task main()
{
	sensorReset(SONAR);

	startTask(readDistance);
	startTask(readColorReflective);
	startTask(controllerTask);
	while(true){
		setMotorSync(RIGHT,LEFT,nTurnRatio,currentPower);
	}
}
